fluidRow(column(12 ,
        bs_accordion_sidebar(id = "acc_Exp2_homemade",
                             spec_side = c(width = 1, offset = 0),
                             spec_main = c(width = 11, offset = 0),
                             position = "right") %>%
          bs_append(title_side = p(icon("table") , "Tables") , 
                    content_side = NULL , 
                    content_main = fluidRow(column(12 ,
                                                   boxPlus(
                                                     closable = FALSE , collapsible = TRUE , collapsed = TRUE ,
                                                     title = "mRNA data table" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                                     enable_sidebar = TRUE,
                                                     sidebar_width = 20,
                                                     sidebar_start_open = FALSE,
                                                     sidebar_content = tagList(checkboxGroupInput("mRNAseqData.selected.columns", p(h4(tags$b("Select columns to show")), style = "text-align:center"),
                                                                                                  colnames(mRNAseqData.full),
                                                                                                  selected = colnames(mRNAseqData.full))),
                                                     DT::dataTableOutput("Homemade_mRNA_table")
                                                   ),
                                                   boxPlus(
                                                     closable = FALSE , collapsible = TRUE , collapsed = TRUE ,
                                                     title = "miR data table" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                                     enable_sidebar = TRUE,
                                                     sidebar_width = 20,
                                                     sidebar_start_open = FALSE,
                                                     sidebar_content = tagList(checkboxGroupInput("miRseqData.selected.columns", p(h4(tags$b("Select columns to show")), style = "text-align:center"),
                                                                                                  colnames(miRseqData.full),
                                                                                                  selected = colnames(miRseqData.full))),
                                                     DT::dataTableOutput("Homemade_miR_table")
                                                   ),
                                                   boxPlus(
                                                     closable = FALSE , collapsible = TRUE , collapsed = TRUE ,
                                                     title = "Protein data table" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                                     enable_sidebar = TRUE,
                                                     sidebar_width = 20,
                                                     sidebar_start_open = FALSE,
                                                     sidebar_content = tagList(checkboxGroupInput("ProteinData.selected.columns", p(h4(tags$b("Select columns to show")), style = "text-align:center"),
                                                                                                  colnames(ProteinData.full),
                                                                                                  selected = colnames(ProteinData.full))),
                                                     DT::dataTableOutput("Homemade_protein_table")
                                                   )))) %>% 
          bs_append(title_side = p(icon("chart-bar") , "Graphs"), 
                    content_side = NULL , 
                    content_main = 
                    div(flipBox(
                      id = 100,
                      main_img = Logo_PCA, 
                      header_img = NULL , 
                      front_title = h3(tags$b("Dimension reductions"), style = "color:#367FA9"),
                      back_title = p(tags$img(src = Logo_Corr , style = "height:05% ; width:05% ; text-align:center"), br(), h3(tags$b("Correlations"), style = "color:#367FA9"), style = "text-align:center"),
                      front_btn_text = "Correlations",
                      back_btn_text = "Dimension reductions",
                      fluidRow(column(4, 
                                      boxPlus(
                                        closable = FALSE , collapsible = TRUE , collapsed = FALSE ,
                                        title = "Bulk mRNA PCA" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                        fluidRow(column (6, selectInput("mRNA.PCA.samples", label = tags$b("Select samples"), 
                                                                        choices = list("All", "Healthy", "DMD"), 
                                                                        selected = "All")),
                                                 column (6, selectInput("mRNA.PCA.legend", label = tags$b("Select the legend"), 
                                                                        choices = list("Cell stage" = 1, "Phenotype" = 2, "Cell line" = 3), 
                                                                        selected = 1))),
                                        fluidRow(column (4, numericInput("mRNA.PCA.threshold", label = tags$b("Select read threshold (*)", style = "color:#CB4A4A"),value = 10)),
                                                 column (4, numericInput("mRNA.PCA.component1", label = tags$b("Select component x"), value = 1)),
                                                 column (4, numericInput("mRNA.PCA.component2", label = tags$b("Select component y"), value = 2))),
                                        plotlyOutput(outputId = "Exp_homemade_PCA.mRNA"), br(),
                                        downloadButton("Exp_homemade_PCA.mRNA.Download", "Download data")
                                      )),
                               column(4, 
                                      boxPlus(
                                        closable = FALSE , collapsible = TRUE , collapsed = FALSE ,
                                        title = "Bulk miR PCA" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                        fluidRow(column (6, selectInput("miR.PCA.samples", label = tags$b("Select samples"), 
                                                                        choices = list("All", "Healthy", "DMD"), 
                                                                        selected = "All")),
                                                 column (6, selectInput("miR.PCA.legend", label = tags$b("Select the legend"), 
                                                                        choices = list("Cell stage" = 1, "Phenotype" = 2, "Cell line" = 3), 
                                                                        selected = 1))),
                                        fluidRow(column (4, numericInput("miR.PCA.threshold", label = tags$b("Select read threshold"), value = 5)),
                                                 column (4, numericInput("miR.PCA.component1", label = tags$b("Select component x"), value = 1)),
                                                 column (4, numericInput("miR.PCA.component2", label = tags$b("Select component y"), value = 2))),
                                        plotlyOutput(outputId = "Exp_homemade_PCA.miR"), br(),
                                        downloadButton("Exp_homemade_PCA.miR.Download", "Download data")
                                      )),
                               column(4, 
                                      boxPlus(
                                        closable = FALSE , collapsible = TRUE , collapsed = FALSE ,
                                        title = "Single-cell mRNA reduction" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                        selectInput("SingleCell.reduction", label = tags$b("Select the reduction"), 
                                                    choices = list("tSNE" = "tsne" , 
                                                                   "UMAP" = "umap",
                                                                   "PCA" = "pca") , 
                                                    selected = "tsne"),
                                        fluidRow(column (6, numericInput("SingleCell.component1", label = tags$b("Select component x"), value = 1)),
                                                 column (6, numericInput("SingleCell.component2", label = tags$b("Select component y"), value = 2))),
                                        plotlyOutput(outputId = "Exp_homemade_SingleCell.reduc"), br(),
                                        downloadButton("Exp_homemade_SingleCell.reduc.Download", "Download data")
                                      ))),
                      back_content = tagList(
                        fluidRow(column(7, 
                                        boxPlus(
                                          closable = FALSE , collapsible = TRUE , collapsed = FALSE , height = 750,
                                          title = "Bulk mRNA correlation" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                          fluidRow(column (4, selectInput("mRNA.corr.samples", label = tags$b("Select samples"), 
                                                                          choices = list("All", "Healthy", "DMD"), 
                                                                          selected = "All")),
                                                   column (4, selectInput("mRNA.corr.method", label = tags$b("Select correlation method (*)", style = "color:#CB4A4A"), 
                                                                          choices = list("pearson", "kendall", "spearman"), 
                                                                          selected = "spearman")),
                                                   column (4, numericInput("mRNA.corr.threshold", label = tags$b("Select read threshold (*)", style = "color:#CB4A4A"), value = 10)),
                                           downloadButton("Exp_homemade_corr.mRNA.Download", "Download data"), br(),
                                           plotlyOutput(outputId = "Exp_homemade_corr.mRNA")
                                          ))), 
                                 column(5, 
                                        boxPlus(
                                          closable = FALSE , collapsible = TRUE , collapsed = FALSE , height = 750,
                                          title = "Bulk miR correlation" , status = "primary" , solidHeader = TRUE , width = 12 ,
                                          fluidRow(column (4, selectInput("miR.corr.samples", label = tags$b("Select samples"), 
                                                                          choices = list("All", "Healthy", "DMD"), 
                                                                          selected = "All")),
                                                   column (4, selectInput("miR.corr.method", label = tags$b("Select correlation method"), 
                                                                          choices = list("pearson", "kendall", "spearman"), 
                                                                          selected = "spearman")),
                                                   column (4, numericInput("miR.corr.threshold", label = tags$b("Select read threshold"), value = 5))),
                                          downloadButton("Exp_homemade_corr.miR.Download", "Download data"), br(),
                                          plotlyOutput(outputId = "Exp_homemade_corr.miR")
                                        ))))
                    ),
                    br(),
                    p(icon("info-circle"), "Data are normalised, centered and reduced.", style = "color:#367FA9"),
                    p(icon("exclamation-triangle"), "(*) Changing these parameters will involve computing time and might take a while.", style = "color:#CB4A4A"),
                    br())),
        use_bs_accordion_sidebar()
        ))